environment:
  global:
    PROJECT_NAME: remacs
  matrix:
    - TARGET: x86_64-pc-windows-gnu

image: Visual Studio 2017

# Install Rust and Cargo
# (Based on from https://github.com/rust-lang/libc/blob/master/appveyor.yml)
install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxillary\Build\vcvarsall.bat" /clean_env
  - set /p REMACS_RUST_VERSION=<rust-toolchain
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe --default-host %TARGET% --default-toolchain %REMACS_RUST_VERSION% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin;C:\msys64\usr\bin
  - rustup component add rustfmt-preview
  - rustc -Vv
  - rustfmt --version
  - cargo -V
  - set MSYSTEM=MINGW64
  - C:\msys64\usr\bin\bash --login -c "pacman -Syy"
  - C:\msys64\usr\bin\bash --login -c "pacman -Syu --noconfirm base-devel"
  - C:\msys64\usr\bin\bash --login -c "pacman -Syu --noconfirm mingw-w64-x86_64-toolchain"
  - C:\msys64\usr\bin\bash --login -c "pacman -Syu --noconfirm mingw-w64-x86_64-xpm-nox mingw-w64-x86_64-libtiff"
  - C:\msys64\usr\bin\bash --login -c "pacman -Syu --noconfirm mingw-w64-x86_64-giflib mingw-w64-x86_64-jbigkit"
  - C:\msys64\usr\bin\bash --login -c "pacman -Syu --noconfirm mingw-w64-x86_64-libpng mingw-w64-x86_64-libjpeg-turbo"
  - C:\msys64\usr\bin\bash --login -c "pacman -Syu --noconfirm mingw-w64-x86_64-librsvg mingw-w64-x86_64-libxml2"
  - C:\msys64\usr\bin\bash --login -c "pacman -Syu --noconfirm mingw-w64-x86_64-gnutls"

# test_script takes care of building for us, so disable Appveyor's
# build stage. This prevents the "directory does not contain a project
# or solution file" error.  source:
# https://github.com/starkat99/appveyor-rust/blob/master/appveyor.yml#L113
build: false

# Equivalent to Travis's `script` phase
test_script:
  - C:\msys64\usr\bin\bash --login -c "cd /c/projects/remacs && ./autogen.sh"
  - C:\msys64\usr\bin\bash --login -c "cd /c/projects/remacs && PKG_CONFIG_PATH=/mingw64/lib/pkgconfig ./configure --without-imagemagick"
  - C:\msys64\usr\bin\bash --login -c "cd /c/projects/remacs && make"
  - C:\msys64\usr\bin\bash --login -c "cd /c/projects/remacs && make check"

branches:
  only:
    - master
