[package]
name = "remacs-lib"
version = "0.1.0"

[dependencies]
rand = "0.3"
libc = "0.2"
errno = "0.2.3"

[lib]
path = "lib.rs"
crate-type = ["staticlib", "rlib"]

[features]
# Treat warnings as a build error on Travis.
strict = []