binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
color = "Auto"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
empty_item_single_line = true
error_on_line_overflow = true
error_on_unformatted = false
fn_args_density = "Tall"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
format_strings = false
hard_tabs = false
imports_indent = "Visual"
imports_layout = "Mixed"
indent_style = "Block"
match_arm_blocks = true
match_block_trailing_comma = false
max_width = 100
merge_derives = true
newline_style = "Unix"
normalize_comments = false
remove_blank_lines_at_start_or_end_of_block = true
reorder_extern_crates = true
reorder_extern_crates_in_group = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
report_fixme = "Never"
report_todo = "Never"
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
spaces_within_parens_and_brackets = false
struct_field_align_threshold = 0
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = false
use_small_heuristics = true
use_try_shorthand = false
where_single_line = false
wrap_comments = false
write_mode = "Overwrite"
